# Generated by Django 3.1.1 on 2020-09-05 15:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0002_app2'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 9, 5, 15, 3, 8, 177084, tzinfo=utc)),
        ),
    ]
